filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/task-manager-kibana.json
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  indices:
    - index: "task-manager-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "http://kibana:5601"
